
# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.3
# Copyright: (c) 2007-2012 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from distutils.core import setup
from py2exe.build_exe import py2exe

import glob
import os
import zlib
import shutil

# Remove the build folder
shutil.rmtree("build", ignore_errors=True)


class Target(object):
    """ A simple class that holds information on our executable file. """
    def __init__(self, **kw):
        """ Default class constructor. Update as you need. """
        self.__dict__.update(kw)
        

# Ok, let's explain why I am doing that.
# Often, data_files, excludes and dll_excludes (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

data_files = [('GUI\AuiPanel', ['F:\\Adel2\\GUI\\AuiPanel\\__init__.pyc',
                                'F:\\Adel2\\GUI\\AuiPanel\\Rev.pyc',
                                'F:\\Adel2\\GUI\\AuiPanel\\Stat.pyc']),
              ('GUI\Edit', ['F:\\Adel2\\GUI\\Edit\\__init__.pyc',
                            'F:\\Adel2\\GUI\\Edit\\accsrh.pyc',
                            'F:\\Adel2\\GUI\\Edit\\buyit.pyc',
                            'F:\\Adel2\\GUI\\Edit\\EDA.pyc',
                            'F:\\Adel2\\GUI\\Edit\\Edacc.pyc',
                            'F:\\Adel2\\GUI\\Edit\\EDM.pyc',
                            'F:\\Adel2\\GUI\\Edit\\Edmolk6.pyc',
                            'F:\\Adel2\\GUI\\Edit\\Edmolk62.pyc',
                            'F:\\Adel2\\GUI\\Edit\\InAcc3.pyc',
                            'F:\\Adel2\\GUI\\Edit\\Pnl0.pyc',
                            'F:\\Adel2\\GUI\\Edit\\Specy.pyc']),
              ('Database', ['F:\\Adel2\\Database\\__init__.pyc',
                            'F:\\Adel2\\Database\\ABR.db',
                            'F:\\Adel2\\Database\\Company.db',
                            'F:\\Adel2\\Database\\DataGet.pyc',
                            'F:\\Adel2\\Database\\Main.db',
                            'F:\\Adel2\\Database\\MDataGet.pyc',
                            'F:\\Adel2\\Database\\Menu.db',
                            'F:\\Adel2\\Database\\MenuSet.pyc',
                            'F:\\Adel2\\Database\\Molk.db',
                            'F:\\Adel2\\Database\\wxsq2.pyc']),
              ('GUI', ['F:\\Adel2\\GUI\\__init__.pyc',
                       'F:\\Adel2\\GUI\\BG.pyc',
                       'F:\\Adel2\\GUI\\MainMenu.pyc',
                       'F:\\Adel2\\GUI\\proman.pyc',
                       'F:\\Adel2\\GUI\\window.pyc']),
              ('GUI\Input', ['F:\\Adel2\\GUI\\Input\\__init__.pyc',
                             'F:\\Adel2\\GUI\\Input\\accsrh.pyc',
                             'F:\\Adel2\\GUI\\Input\\buyit.pyc',
                             'F:\\Adel2\\GUI\\Input\\IAc.pyc',
                             'F:\\Adel2\\GUI\\Input\\IMK.pyc',
                             'F:\\Adel2\\GUI\\Input\\InAcc3.pyc',
                             'F:\\Adel2\\GUI\\Input\\InM6.pyc',
                             'F:\\Adel2\\GUI\\Input\\InMolk61.pyc',
                             'F:\\Adel2\\GUI\\Input\\InMolk62.pyc',
                             'F:\\Adel2\\GUI\\Input\\Pmenu.pyc',
                             'F:\\Adel2\\GUI\\Input\\Pnl0.pyc',
                             'F:\\Adel2\\GUI\\Input\\Specy.pyc']),
              ('GUI\Program', ['F:\\Adel2\\GUI\\Program\\quit.pyc',
                               'F:\\Adel2\\GUI\\Program\\DEF.pyc',
                               'F:\\Adel2\\GUI\\Program\\defin2.pyc',
                               'F:\\Adel2\\GUI\\Program\\Pnl0.pyc',
                               'F:\\Adel2\\GUI\\Program\\pro1.pyc',
                               'F:\\Adel2\\GUI\\Program\\proper.pyc']),
              ('GUI\Report', ['F:\\Adel2\\GUI\\Report\\__init__.pyc',
                              'F:\\Adel2\\GUI\\Report\\AD1.pyc',
                              'F:\\Adel2\\GUI\\Report\\ADftar.pyc',
                              'F:\\Adel2\\GUI\\Report\\buyit.pyc',
                              'F:\\Adel2\\GUI\\Report\\MD1.pyc',
                              'F:\\Adel2\\GUI\\Report\\MD2.pyc',
                              'F:\\Adel2\\GUI\\Report\\MDftar1.pyc',
                              'F:\\Adel2\\GUI\\Report\\MDftar4.pyc',
                              'F:\\Adel2\\GUI\\Report\\Pnl0.pyc',
                              'F:\\Adel2\\GUI\\Report\\RMolk61.pyc',
                              'F:\\Adel2\\GUI\\Report\\RMolk62.pyc',
                              'F:\\Adel2\\GUI\\Report\\Specy.pyc']),
              ('GUI\Develop', ['F:\\Adel2\\GUI\\Develop\\__init__.pyc',
                               'F:\\Adel2\\GUI\\Develop\\buyit.pyc',
                               'F:\\Adel2\\GUI\\Develop\\Pnl0.pyc']),
              ('GUI\Help', ['F:\\Adel2\\GUI\\Help\\__init__.pyc',
                            'F:\\Adel2\\GUI\\Help\\about.pyc',
                            'F:\\Adel2\\GUI\\Help\\Pnl0.pyc']),
              ('GUI\Connect', ['F:\\Adel2\\GUI\\Connect\\__init__.pyc',
                               'F:\\Adel2\\GUI\\Connect\\buyit.pyc',
                               'F:\\Adel2\\GUI\\Connect\\Pnl0.pyc']),
              ('Config', ['F:\\Adel2\\Config\\__init__.pyc',
                          'F:\\Adel2\\Config\\config.pyc',
                          'F:\\Adel2\\Config\\Init.pyc',
                          'F:\\Adel2\\Config\\program.ini']),
              ('Utility', ['F:\\Adel2\\Utility\\__init__.pyc',
                           'F:\\Adel2\\Utility\\Adaad2.pyc',
                           'F:\\Adel2\\Utility\\adadfa1',
                           'F:\\Adel2\\Utility\\B1.pyc',
                           'F:\\Adel2\\Utility\\barcode.png',
                           'F:\\Adel2\\Utility\\calcu.pyc',
                           'F:\\Adel2\\Utility\\calculator.bmp',
                           'F:\\Adel2\\Utility\\calfar01.pyc',
                           'F:\\Adel2\\Utility\\clacal3.pyc',
                           'F:\\Adel2\\Utility\\fakey.pyc'])]

includes = ['khayyam', 'wx', 'wx.dataview', 'wx.lib']
excludes = ['_gtkagg', '_tkagg', 'bsddb', 'curses', 'email', 'pywin.debugger',
            'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl',
            'Tkconstants', 'Tkinter']
packages = ['Config', 'Database', 'GUI', 'GUI.AuiPanel', 'GUI.Connect',
            'GUI.Develop', 'GUI.Edit', 'GUI.Help', 'GUI.Input',
            'GUI.Program', 'GUI.Report', 'Utility']
dll_excludes = ['libgdk-win32-2.0-0.dll', 'libgobject-2.0-0.dll', 'tcl84.dll',
                'tk84.dll']
icon_resources = [(1, 'F:\\Adel2\\Res\\Icons\\f4.ico'), (2, 'F:\\Adel2\\Res\\Icons\\U5.ico')]
bitmap_resources = [(1, 'F:\\Adel2\\Utility\\calculator.bmp')]
other_resources = [(4, 24, 'F:\\Adel2\\Res\\Pics\\B10.jpg'), (5, 24, 'F:\\Adel2\\Res\\Pics\\B11.jpg'),
                   (6, 24, 'F:\\Adel2\\Res\\Pics\\B13.jpg'),
                   (7, 24, 'F:\\Adel2\\Res\\Pics\\B14.jpg'),
                   (8, 24, 'F:\\Adel2\\Res\\Pics\\B16.jpg'),
                   (1, 24, 'F:\\Adel2\\Res\\Pics\\B6.jpg'),
                   (2, 24, 'F:\\Adel2\\Res\\Pics\\B7.jpg'),
                   (3, 24, 'F:\\Adel2\\Res\\Pics\\B8.jpg')]


# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# Ok, now we are going to build our target class.
# I chose this building strategy as it works perfectly for me :-D

GUI2Exe_Target_1 = Target(
    # what to build
    script = "mainpro.py",
    icon_resources = icon_resources,
    bitmap_resources = bitmap_resources,
    other_resources = other_resources,
    dest_base = "mainpro",    
    version = "0.1",
    company_name = "Chashme",
    copyright = "Cheshme",
    name = "Py2Exe Sample File",
    
    )

# No custom class for UPX compression or Inno Setup script

# That's serious now: we have all (or almost all) the options py2exe
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.
                    
setup(

    # No UPX or Inno Setup

    data_files = data_files,

    options = {"py2exe": {"compressed": 0, 
                          "optimize": 0,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dll_excludes": dll_excludes,
                          "bundle_files": 3,
                          "dist_dir": "dist",
                          "xref": False,
                          "skip_archive": False,
                          "ascii": False,
                          "custom_boot_script": '',
                         }
              },

    zipfile = None,
    console = [],
    windows = [GUI2Exe_Target_1],
    service = [],
    com_server = [],
    ctypes_com_server = []
    )

# This is a place where any post-compile code may go.
# You can add as much code as you want, which can be used, for example,
# to clean up your folders or to do some particular post-compilation
# actions.

# No post-compilation code added


# And we are done. That's a setup script :-D

